channelstut/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from exampleChan import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('exampleChan.urls', namespace='exampleChan')),
]

exampleChan/urls.py
from django.conf.urls import url
from views import log_in, log_out, sign_up, user_list


urlpatterns = [
    url(r'^log_in/$', log_in, name='log_in'),
    url(r'^log_out/$', log_out, name='log_out'),
    url(r'^sign_up/$', sign_up, name='sign_up'),
    url(r'^$', user_list, name='user_list'),
]

exampleChan/models.py
from django.conf import settings
from django.db import models


class LoggedInUser(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='logged_in_user')

exampleChan/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect


User = get_user_model()


@login_required(login_url='/log_in/')
def user_list(request):
    """
    NOTE: This is fine for demonstration purposes, but this should be
    refactored before we deploy this app to production.
    Imagine how 100,000 users logging in and out of our app would affect
    the performance of this code!
    """
    users = User.objects.select_related('logged_in_user')
    for user in users:
        user.status = 'Online' if hasattr(user, 'logged_in_user') else 'Offline'
    return render(request, 'exampleChan/user_list.html', {'users': users})


def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('exampleChan:user_list'))
        else:
            print form.errors
    return render(request, 'exampleChan/log_in.html', {'form': form})


@login_required(login_url='/log_in/')
def log_out(request):
    logout(request)
    return redirect(reverse('exampleChan:log_in'))


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('exampleChan:log_in'))
        else:
            print form.errors
    return render(request, 'exampleChan/sign_up.html', {'form': form})

exampleChan/templates/exampleChan/_base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <title>Example Channels</title>
</head>
<body>
  <div class="container">
    <br>
    {% block content %}{% endblock content %}
  </div>
  <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
  {% block script %}{% endblock script %}
</body>
</html>

exampleChan/templates/exampleChan/log_in.html
{% extends 'exampleChan/_base.html' %}

{% block content %}
  <form action="{% url 'exampleChan:log_in' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Log in</button>
  </form>
  <p>Don't have an account? <a href="{% url 'exampleChan:sign_up' %}">Sign up!</a></p>
{% endblock content %}

exampleChan/templates/exampleChan/sign_up.html
{% extends 'exampleChan/_base.html' %}

{% block content %}
  <form action="{% url 'exampleChan:sign_up' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Sign up</button>
    <p>Already have an account? <a href="{% url 'exampleChan:log_in' %}">Log in!</a></p>
  </form>
{% endblock content %}

exampleChan/templates/exampleChan/user_list.html
{% extends 'exampleChan/_base.html' %}

{% block content %}
  <a href="{% url 'exampleChan:log_out' %}">Log out</a>
  <br>
  <br>
  <input type="text" id='sender' size='60'>
  <button id="submit">Submit</button>
  <br><br>
  <p id='messages'></p>
{% endblock content %}

{% block script %}
  <script>
    var socket = new WebSocket('wss://' + window.location.host + '/users/');

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
    };

    socket.onmessage = function message(event) {
      var data = JSON.parse(event.data);
      // NOTE: We escape JavaScript to prevent XSS attacks.
      console.log(data);
      var msg = data['msg'];
      if (msg.length>0){
        var p = document.getElementById('messages');
        p.innerHTML += '<p>' + msg + '</p>';
        }
    };

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }

    document.getElementById('submit').onclick = function() {
      if ($('#sender').val() != ""){
        socket.send($('#sender').val());
        document.getElementById('sender').value = ""
      }
    }
  </script>
{% endblock script %}